Added XTags
CryptoMorin/XSeries pull request #150
Opened 2021-12-11 14:39 UTC by RohanGoyalDev

A possible replacement for  [Spigot's Tag system](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Tag.html) that can be used for 1.8 and can have XSound, XBlock, XParticle genericised later on to ease in finding enum values that all carry a common property

2021-12-11 17:46 UTC, RohanGoyalDev commented
I'll add back generics later, didn't see he removed them

2021-12-12 03:13 UTC, CryptoMorin requested changes

2021-12-12 03:13 UTC, CryptoMorin commented on src/main/java/com/cryptomorin/xseries/XMaterial.java
> +    public static Set<XMaterial> filterSupported(Set<XMaterial> materials) {
Why is this useful?

2021-12-12 03:13 UTC, CryptoMorin commented on src/test/XTagTest.java
> +  void checkInheritTag() {
You should add all tests to `Tests` class. I personally don't see the point of separating these.

2021-12-12 03:13 UTC, CryptoMorin commented on src/main/java/com/cryptomorin/xseries/XTag.java
> +public final class XTag {
Wouldn't it make more sense to use an enum to avoid this mess?

2021-12-12 03:18 UTC, CryptoMorin commented
I'm personally not that familiar with tags, but have you looked at [XMaterialUtil](https://github.com/CryptoMorin/XSeries/blob/master/src/main/java/com/cryptomorin/xseries/XMaterialUtil.java)? Should we remove that and merge it with XTag?

> can have XSound, XBlock, XParticle genericised later on to ease in finding enum values that all carry a common property
Also, if this means changing those classes, discuss this before making any changes.

2021-12-12 03:28 UTC, CryptoMorin commented on src/main/java/com/cryptomorin/xseries/XTag.java
> +public final class XTag {
Also, using static imports sounds reasonable at this point.

2021-12-12 03:29 UTC, CryptoMorin commented on src/main/java/com/cryptomorin/xseries/XTag.java
> +            Collections.unmodifiableSet(new HashSet<>(Arrays.asList(values)));
Use an EnumSet

2021-12-12 06:41 UTC, RohanGoyalDev commented
> I'm personally not that familiar with tags, but have you looked at [XMaterialUtil](https://github.com/CryptoMorin/XSeries/blob/master/src/main/java/com/cryptomorin/xseries/XMaterialUtil.java)? Should we remove that and merge it with XTag?
> 
> > can have XSound, XBlock, XParticle genericised later on to ease in finding enum values that all carry a common property
> 
> Also, if this means changing those classes, discuss this before making any changes.

Anything that is an enum can be used under XTag, so XBlock and XParticle can't rn but XPotion, XSound, XBiome, XEnchantment can without any changes in those enums

2021-12-14 03:03 UTC, CryptoMorin commented
I think you should really fix the enum issue before adding more stuff.

2021-12-15 12:48 UTC, RohanGoyalDev commented
> I think you should really fix the enum issue before adding more stuff.

Can you gimme like an example or class hierarchy? I thought of many ways to use an enum for this but all of them still create a mess

2021-12-15 14:57 UTC, CryptoMorin commented
Hmm, yeah you're right, after trying a few methods myself there's no way to make this cleaner while keeping the type safety or the cleanness from an API perspective.

2021-12-16 13:20 UTC, RohanGoyalDev commented
I will keep adding more Tags. If you or anyone else has a good idea on cleanup gimme an example and ill refactor the code accordingly if that works

2021-12-17 12:48 UTC, CryptoMorin commented
I think we should support tagged mappings too.
isTagged will still return a boolean without being affected, but we can add a new method of(key)
The only tradeoff is the performance and memory of `EnumMap` which will be extremely memory inefficient for a class like XMaterial because it has a lot of enums since `EnumMap` doesn't do Jumbo optimizations.

We can fix that if we make our own wrapper.
https://pastebin.com/BQEBypwb

Btw while testing this I noticed you did this:
```java
if (this.values.isEmpty()) newValues = EnumSet.copyOf((EnumSet<T>) this.values);
else newValues = EnumSet.copyOf(this.values);
```
There's no difference between these two lines, was this intentional?



We could also take Spigot's approach and use a switch statement in a simple static method instead of a map.

2021-12-17 15:36 UTC, RohanGoyalDev commented
> ```java
> if (this.values.isEmpty()) newValues = EnumSet.copyOf((EnumSet<T>) this.values);
> else newValues = EnumSet.copyOf(this.values);
> ```


Well those lines are intentional because of the illegal argument that `EnumSet.copyOf()` throws when the `Collection` passed in as a parameter is empty. And there are Tags like `ITEMS_FURNACE_MATERIALS` which are for some apparent reason left empty in spigot 1.18. To account for those and the tags that just inherit values from other tags and have no seperate value I had to made a seperate constructor because `T.class` is not a thing and `EnumSet.noneOf()` needs that, if i try to solve both of those issues then I cant make the `values` class variable an unmodifiable set because `Collections.unModifiableSet()` returns a set that cant be casted to `EnumSet`

2021-12-17 15:37 UTC, RohanGoyalDev commented
> > ```java
> > if (this.values.isEmpty()) newValues = EnumSet.copyOf((EnumSet<T>) this.values);
> > else newValues = EnumSet.copyOf(this.values);
> > ```
> 
> Well those lines are intentional because of the illegal argument exception that `EnumSet.copyOf()` throws when the `Collection` passed in as a parameter is empty UNLESS its another `EnumSet`. And there are Tags like `ITEMS_FURNACE_MATERIALS` which are for some apparent reason left empty in spigot 1.18. To account for those and the tags that just inherit values from other tags and have no seperate value I had to made a seperate constructor because `T.class` is not a thing and `EnumSet.noneOf()` needs that, if i try to solve both of those issues then I cant make the `values` class variable an unmodifiable set because `Collections.unModifiableSet()` returns a set that cant be casted to `EnumSet`

2021-12-30 03:04 UTC, CryptoMorin commented
If you're done with this, tell me to merge it.

2021-12-31 11:58 UTC, RohanGoyalDev commented
I think its done for now apart from the tagged mappings. I'll keep adding more tags which i see useful in more pull requests later on

2022-01-01 03:09 UTC, merged